FROM ruby:3.2

RUN apt-get update && apt-get install -y \
    build-essential \
    ffmpeg \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

RUN bundle install

CMD ["ruby", "--mjit", "./bot", "--server=http://telegram-bot-api:8081"]
